configfile: "workflow/config/config.yaml"

include: "rules/1_assembly.smk"


rule all:
    input:
        # Assembly
        expand("results/Genomics/1_Assembly/2_Assemblers/flye/{process}/assembly.fasta",
            process=["raw"]),

        # QUAST
        expand("results/Genomics/1_Assembly/3_Evaluation/quast/flye/raw/")
